#!/bin/sh
# Параметры live-build для HackOS.
set -e

lb config noauto \
  --mode debian \
  --distribution bookworm \
  --architectures amd64 \
  --linux-flavours amd64 \
  --binary-images iso-hybrid \
  --bootloaders "grub-efi,syslinux" \
  --debian-installer live \
  --archive-areas "main contrib non-free non-free-firmware" \
  --iso-application "HackOS" \
  --iso-publisher "HackOS" \
  --iso-volume "HackOS" \
  --bootappend-live "boot=live components hostname=hackos username=user" \
  "${@}"
